name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    # Use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the master branch
    - uses: actions/checkout@v2
      with:
          lfs: true
          token: ${{ secrets.ACCESS_TOKEN }}
    # Configure Git (if necessary)
    - name: Configure Git
      run: |
        git config --global user.name "ABritex"
        git config --global user.email "aprelox@gmail.com"

    
    - name: Clean up git worktrees
      run: git worktree prune || true

    # Create the deployment folder if it doesn't exist
    - name: Create deployment folder
      run: mkdir -p github-pages-deploy-action-temp-deployment-folder

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Publish .NET Core Project
      run: dotnet publish Sanctum -c Release -o release --nologo

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
